gmail: "urappzone@gmail.com"
gmail_password: "N/A"
domain: "urappzone.com"
facebook_key: "411758708954101"
facebook_secret: "0c1ed04a80510128d40f9d414d7c7e45"
linkedin_key: "7737tupvn54tc1"
linkedin_secret: "cBKl6BVhmz3kcTVZ"
google_key: "151107670704.apps.googleusercontent.com"
google_secret: "BV4aYdNAlTL45hqn5_5HQYs3"
twitter_key:  "QCXnlaBDFR8dObeOwubsw"
twitter_secret: "LZ0iHB9oQtUD4Q4Y6ajHI1yxzWzpm5YRo2Xn7QHA"
